Validate trial name and folder (#62)
* validate folder

* fix vars for ui assets

* change terraform workspace name

* remove obsolete fields from definition

* fix copy of assets

diff --git a/.github/workflows/terraform-plan-apply.yml b/.github/workflows/terraform-plan-apply.yml
--- a/.github/workflows/terraform-plan-apply.yml
+++ b/.github/workflows/terraform-plan-apply.yml
@@ -20,7 +20,9 @@ jobs:
         id: calc_files_diff
         run: |
           set -o errexit
+          set -o pipefail
           set -o nounset
+          # set -o xtrace
 
           git fetch origin main:localmain
 
@@ -61,10 +63,19 @@ jobs:
             echo "current definition file path: $path"
 
             # Extract values for the trial
-            trialName=$(jq -r '.name' ./$path)
-            trialId=$(jq -r '.id' ./$path)
+            trial_name=$(jq -r '.name' ./$path)
             trial_dir=$(dirname $(realpath $path))
-            MatrixItem="{\"trial_id\": \"$trialId\", \"path\": \"$path\", \"trial_name\": \"$trialName\", \"trial_dir\": \"$trial_dir\",},"
+
+            # Check that trial name in the json equals to its folder name.
+            last_dir_name=$(basename $trial_dir)
+            if [[ "$last_dir_name" != "$trial_name" ]]
+            then
+              echo "ERROR: trial name (${trial_name}) is not equal to its folder (${last_dir_name})." >&2
+              exit 1
+            fi
+
+            # Prepare the matrix item
+            MatrixItem="{\"trial_name\": \"$trial_name\", \"trial_dir\": \"$trial_dir\",},"
 
             JSON="$JSON$MatrixItem"
           done <<< "$FILES"
@@ -80,7 +91,7 @@ jobs:
           echo "::set-output name=matrix::$( echo "$JSON" )"
 
   deploy:
-    name: "Execute TF on ${{ matrix.trial_name }}: ${{ matrix.path }}"
+    name: "Execute Terraform"
     needs: prepare-run-matrix
     if: ${{ needs.prepare-run-matrix.outputs.is_empty_matrix == 'false' }}
     strategy:
@@ -107,12 +118,21 @@ jobs:
         run: terraform init
 
       - name: Terraform workspace
-        run: terraform workspace select ${{ matrix.trial_id }} || terraform workspace new ${{ matrix.trial_id }}
+        run: |
+          set -o errexit
+          set -o pipefail
+          set -o nounset
+          # set -o xtrace
+
+          # github ref comes with "/" which is not valid for workspace names
+          ref_for_workspace="${GITHUB_REF//\//_}"
+          workspace_name="${{ matrix.trial_name }}-${ref_for_workspace}"
+          terraform workspace select ${workspace_name} || terraform workspace new ${workspace_name}
 
       - name: Terraform Format
         run: terraform fmt -check
 
-      - name: Prepare tfvars file
+      - name: Prepare deployment variables
         env:
           TFVARS_TEMPLATE: 'tfvars.template'
         run: |
@@ -150,23 +170,33 @@ jobs:
 
           cat ${{ matrix.trial_name }}.tfvars
 
+          # extract more values from the definition file
+          echo "tenant_id=$(jq -r '.tenant_id' ${definition_path})" >> $GITHUB_ENV
+          echo "ui_client_id=$(jq -r '.ui_client_id' ${definition_path})" >> $GITHUB_ENV
+
       # Plan TF
-      - name: Plan TF for "${{ matrix.trial_name }}"
+      - name: Terraform plan
         run: |
           set -o errexit
+          set -o pipefail
           set -o nounset
+          # set -o xtrace
 
-          terraform plan -var-file=${{ matrix.trial_name }}.tfvars -var="owner=${{ github.actor }}"
+          terraform plan -out=tfplan -var-file=${{ matrix.trial_name }}.tfvars \
+            -var="owner=${{ github.actor }}" \
+            -var="github_ref=${{ github.ref }}"
 
       # Apply, only on merge to main
-      - name: Apply TF for "${{ matrix.trial_name }}"
+      - name: Terraform apply
         # if: github.ref == 'refs/heads/main'
         run: |
           set -o errexit
+          set -o pipefail
           set -o nounset
+          # set -o xtrace
 
           echo "Merged to main. applying trial's RG"
-          terraform apply -var-file=${{ matrix.trial_name }}.tfvars -var="owner=${{ github.actor }}" -auto-approve
+          terraform apply -auto-approve tfplan
 
           # '-raw' is important so no other characters will be added
           ui_storage_conn_string=$(terraform output -raw ui_conn_string)
@@ -174,10 +204,6 @@ jobs:
           # create an env var from the connection string, so will be available for the later steps
           echo "ui_storage_conn_string=$ui_storage_conn_string" >> $GITHUB_ENV
           echo "gateway_host_string=$gateway_host_string" >> $GITHUB_ENV
-          echo "trial_path=${{ matrix.trial_dir }}" >> $GITHUB_ENV
-          echo "trial_name=${{ matrix.trial_name }}" >> $GITHUB_ENV
-          echo "tenant_id=${{ matrix.tenant_id }}" >> $GITHUB_ENV
-          echo "ui_client_id=${{ matrix.ui_client_id }}" >> $GITHUB_ENV
 
           ## DO NOT DELETE ##
           # mask this value so this sensitive data won't be logged.
@@ -195,30 +221,41 @@ jobs:
       - name: UI component - Unzip and modify
         run: |
           set -o errexit
+          set -o pipefail
           set -o nounset
+          # set -o xtrace
 
           unzip mts-trial-ui.zip
 
-          sed -i 's/{{clientId}}/${{ env.ui_client_id }}/' mts-trial-ui/index.html
-          sed -i 's/{{issuerUrl}}/https:\/\/login.microsoftonline.com\/${{ env.tenant_id }}\/v2.0/' mts-trial-ui/index.html
-          sed -i 's/{{trialName}}/${{ env.trial_name }}/' mts-trial-ui/index.html
-          sed -i 's^{{gatewayUrl}}^${{ env.gateway_host_string }}/api^' mts-trial-ui/index.html
+          index_file="mts-trial-ui/index.html"
+          # sed doesn't like the github {{ }} vars, so dropping the value to a regular var
+          trial_name=${{ matrix.trial_name }}
+
+          sed -i "s/{{clientId}}/${ui_client_id}/" ${index_file}
+          sed -i "s/{{issuerUrl}}/https:\/\/login.microsoftonline.com\/${tenant_id}\/v2.0/" ${index_file}
+          sed -i "s/{{trialName}}/${trial_name}/" ${index_file}
+          sed -i "s^{{gatewayUrl}}^${gateway_host_string}/api^" ${index_file}
 
       # Add Branding Assets
-      - name: UI component - Copy Logo File
+      - name: UI component - copy assets
         run: |
           set -o errexit
+          set -o pipefail
           set -o nounset
+          # set -o xtrace
 
-          echo "using trial path '${{ env.trial_path }}'"
-          cp ${{ env.trial_path }}/assets/branding/img/logo.png mts-trial-ui/assets/branding/img/
+          echo "using trial path ${{ matrix.trial_dir }}"
+          # copy everything in the assets folder
+          cp -fr ${{ matrix.trial_dir }}/assets/* mts-trial-ui/assets/
 
       # Upload to storage account (to $web container)
       - name: UI component - Upload to storage
         # if: github.ref == 'refs/heads/main'
         run: |
           set -o errexit
+          set -o pipefail
           set -o nounset
+          # set -o xtrace
 
           # first clean up the container, then upload the new assets
           az storage blob delete-batch --connection-string ${ui_storage_conn_string} --source "\$web" --pattern "*"
@@ -226,7 +263,7 @@ jobs:
 
   deployall:
     runs-on: ubuntu-latest
-    name: TF plan/apply (matrix)
+    name: Terraform plan/apply (matrix)
     needs: deploy
     steps:
       - name: Check TF (plan) matrix status
