[ARTS-351] - Report init status to CI pipeline (#76)
* pass github commit sha to init service

* test sha

* test commit sha

* get commit sha and pass to TF

* test

* revert changes

* terraform fmt -recursive

* add var to root main

* sample3

* adding init storage account

* storage container for init

* trail4

* fix error with sample

* add .primary_connection_string for env var

* fix bug in output var init_storage_conn_string

* remove blob

* mount init-service to azure files share

* mount init service to azure file share + guy2

* temporary separate init service module from gnric

* fix bug in module name

* fix bug2

* test object type

* test object(...)

* fix var

* test fix

* try flating settings for storage_account attr

* change to array of storage account

* test inline

* fix for storage_account

* fix a typo

* remove sample1

* guy3

* format

* change the if condition to count

* guy2->guy3

* test

* fix typo

* fix default values for vars

* duplicate generic service

* change source

* change init progress env name

* bf98eb59fa1a78d082ac78052b8fba86552713b3

* download init log file

* test download file

* fix typo

* guy5

* fix typo in share name

* guy1

* guy2

* guy10

* pass vars to $GITHUB_ENV

* guy11

* guy12

* guy13 - remove errexit so it won't exit on fail

* guy14

* guy14.2 - pipefail

* guy15

* guy15.3 fail

* guy15.4 fail with timeout

* guy15.5 Timeout

* guy15.6 test with 2 min per loop

* guy15.6 2min per loop

* add decrimental wait + exit on failure / sucess

* change sha for init

* guy15.7

* guy15.8

* guy15.8 test with sample2

* remove dns_zone_name

* fix two outputs after merge

* guy16

* guy16.2

* print log.txt file

* guy17

* Update .github/workflows/terraform-plan-apply.yml

Co-authored-by: Elad Iwanir <13205761+eladiw@users.noreply.github.com>

* Update .github/workflows/terraform-plan-apply.yml

Co-authored-by: Elad Iwanir <13205761+eladiw@users.noreply.github.com>

* pr review comments

* arts351-guy18

* guy19 - adding two more loop iterations

* merge from arts351

* guy20-fail

* guy20-fail

* change progress env var to match init-service PR

* Update .github/workflows/terraform-plan-apply.yml

Co-authored-by: Elad Iwanir <13205761+eladiw@users.noreply.github.com>

* improve loop

* guy20

* guy20

* guy21

* guy21

* guy20 fixed

* guy20.1

* guy22

* guy23

* guy23

* guy23 -68de7405e341182a6411267916b1a4f8e4e5a854

* guy24

* guy25-fail-practitioner-test

* guy26-fail-with-timeout

* removing test

* convert storage_account vars to object({})

* guy27

* guy27.2

* guy28

* guy28.3 dynamic block

* guy28.4 - dynamic storage_account

* guy28.5 change to map

* guy28.6 array of objects

* guy28.7

* guy28.8

* guy29 - refactor TF

* guy29.2 refactor

* guy29.3 - refactor TF

* guy29.4 optional

* guy29.5

* guy29.6

* guy29.7 default null

* guy29.8 [1]:[]

* guy29.9 [var]

* guy29.10 count

* guy29.11 list to map

* guy29.12 list(map(string))

* guy29.13 list(object()) value.

* guy29.14 list(object) value.

* guy29.15

* guy29.16 list(map())

* guy29.17

* guy29.19

* guy29.20

* guy29.21

* guy29.22

* guy29.23

* guy29.24 locals

* guy29.25 locals

* guy29.26 locals

* guy30

* guy30.2 eastus2

* guy31.1

* guy31.1

* remove trail for merge

* PR comments

* fix format

* fix label

* guy32

* guy32.2

* guy32.3

* guy32.4

* guy32.5

* removing trail

* rerunning ci

* rerunning CI

Co-authored-by: Elad Iwanir <13205761+eladiw@users.noreply.github.com>

diff --git a/.github/workflows/terraform-plan-apply.yml b/.github/workflows/terraform-plan-apply.yml
--- a/.github/workflows/terraform-plan-apply.yml
+++ b/.github/workflows/terraform-plan-apply.yml
@@ -261,6 +261,11 @@ jobs:
 
           # '-raw' is important so no other characters will be added
           ui_storage_conn_string=$(terraform output -raw ui_conn_string)
+          init_storage_conn_string=$(terraform output -raw init_storage_conn_string)
+          echo "init_storage_conn_string=$init_storage_conn_string" >> $GITHUB_ENV
+          init_storage_share_name=$(terraform output -raw init_storage_share_name)
+          echo "init_storage_share_name=$init_storage_share_name" >> $GITHUB_ENV
+
           gateway_host_string=$(terraform output -raw gateway_host)
           # create an env var from the connection string, so will be available for the later steps
           echo "ui_storage_conn_string=$ui_storage_conn_string" >> $GITHUB_ENV
@@ -322,6 +327,36 @@ jobs:
           az storage blob delete-batch --connection-string ${ui_storage_conn_string} --source "\$web" --pattern "*"
           az storage blob upload-batch --connection-string ${ui_storage_conn_string} --source mts-trial-ui --destination '$web'
 
+      # Download init service progress log file from azure file share and validate success
+      - name: Validate Init service progress
+        timeout-minutes: 30
+        # if: github.ref == 'refs/heads/main'
+        run: |
+          set -o nounset
+          #set -o xtrace
+          # can't use errexit and pipefail flags here becasue tail will fail if the file doesn't exists
+
+          echo "trying to fetch init service log in loop, timeout set to 30 min."
+          while [ true ]
+          do
+            sleep 10
+            az storage file download --no-progress --path log.txt --share-name ${init_storage_share_name} --connection-string ${init_storage_conn_string} && cat log.txt
+
+            # chainging result with no-op command so git workflow won't fail and seperating command and condition to avoid "unary operator expected" error
+            tail log.txt --lines 1 | grep -q "FAILURE" && :
+            if [ $? -eq 0 ]
+            then
+                echo "Init service - Completed with failure"
+                exit 1
+            fi
+
+            tail log.txt --lines 1 | grep -q "SUCCESS" && :
+            if [ $? -eq 0 ]
+            then
+                echo "Init service - Completed Successfully"
+                exit 0
+            fi
+          done
   deployall:
     runs-on: ubuntu-latest
     name: Terraform plan/apply (matrix)
